---

- name: docker is installed
  become: "yes"
  package:
    name: "{{ item }}"
  when: dockerenv.stat.exists == False
  with_items:
    - "docker"
    - "docker-compose"

- name: docker group
  become: "yes"
  group:
    name: docker
    state: present

- name: current user is in docker group
  become: "yes"
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: "yes"

- name: Docker is enabled
  become: "yes"
  service:
    name: docker
    enabled: "yes"
  # Don't run this task if running inside a docker container (e.g. Travis)
  when: dockerenv.stat.exists == False
