---

- name: mkdir neovim
  file:
    state: directory
    path: "{{ item }}"
    recurse: "yes"
  loop:
    - "~/.local/share/nvim/site/autoload"
    - "~/.config/nvim/lua/config"

- name: configuration files are linked
  file:
    state: link
    force: yes
    src: "{{ role_path }}/files/{{ item }}"
    path: "~/.config/nvim/{{ item }}"
  loop:
    - "init.lua"
    - "lua/config/lazy.lua"
  register: configuration_result

- name: dependencies installed
  become: "yes"
  package:
    name: "{{ item }}"
  loop:
    - nodejs
    - npm
    - python3-neovim
    - cmake
    - g++
